apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: aoojkxd7e-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aoojkxd7e-go 
  name: aoojkxd7e-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: aoojkxd7e-go 
